# Errメソッド {#errメソッド .View_chapterTitle__tslMs}


::: {style="width:35px;height:35px"}
![さき(H.Saki)](https://res.cloudinary.com/zenn/image/fetch/s--FESoQ9n2--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_70/https://storage.googleapis.com/zenn-user-upload/avatar/51291e09a0.jpeg){.AvatarImage_border__33_UE
.AvatarImage_plain__BCJNs width="35" height="35" loading="lazy"
referrerpolicy="no-referrer"}
:::

::: {.UserLinkSmall_text__2BG_S style="width:calc(100% - 35px);font-size:0.87rem"}
::: UserLinkSmall_name__eqTEi
さき(H.Saki)
:::

::: UserLinkSmall_additionalText__2MgRM
2021.08.28に更新
:::
:::
:::
:::

::: ViewerWrapper_container__Cg8HA
[]{style="display:block;width:1px;height:2.7rem;flex-shrink:0"}

::: {.ChapterToc_containerOpen__XEx_6 .ChapterToc_container__mDJhZ}
::: ChapterToc_titleContainer__3Fx5b
このチャプターの目次![](data:image/svg+xml;base64,PHN2ZyB2aWV3Ym94PSIwIDAgMjcgMjciIHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiIgY2xhc3M9IkNoYXB0ZXJUb2NfdG9nZ2xlSWNvbl9fNERfVlQiPjxwYXRoIGZpbGw9ImN1cnJlbnRDb2xvciIgZD0iTTEyLjc0IDIwLjUzbC05LjI2LTkuMThhLjc1Ljc1IDAgMDEwLTEuMDdsMS4yMy0xLjIzYS43NS43NSAwIDAxMS4wNyAwbDcuNDkgNy40MSA3LjQ5LTcuNDFhLjc0Ljc0IDAgMDExLjA2IDBsMS4yNCAxLjIzYS43Ny43NyAwIDAxMCAxLjA3bC05LjI2IDkuMThhLjc0Ljc0IDAgMDEtMS4wNiAweiI+PC9wYXRoPjwvc3ZnPg==){.ChapterToc_toggleIcon__4D_VT}
:::

::: ChapterToc_toc__8_UcH
1.  [この章について](#%E3%81%93%E3%81%AE%E7%AB%A0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)
2.  [キャンセルか、タイムアウトか](#%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB%E3%81%8B%E3%80%81%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%A2%E3%82%A6%E3%83%88%E3%81%8B)
3.  [contextパッケージに存在する2種類のエラー変数](#context%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AB%E5%AD%98%E5%9C%A8%E3%81%99%E3%82%8B2%E7%A8%AE%E9%A1%9E%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E5%A4%89%E6%95%B0)
4.  [Errメソッド](#err%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89)
:::
:::

::: {#viewer-toc}
::: {.znc .BodyContent_anchorToHeadings__Vl0_u}
# [](#%E3%81%93%E3%81%AE%E7%AB%A0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6){.header-anchor-link} この章について {#%E3%81%93%E3%81%AE%E7%AB%A0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6}

この章では、contextに含まれている`Err`メソッドの概要・使いどころについて説明します。

# [](#%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB%E3%81%8B%E3%80%81%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%A2%E3%82%A6%E3%83%88%E3%81%8B){.header-anchor-link} キャンセルか、タイムアウトか {#%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB%E3%81%8B%E3%80%81%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%A2%E3%82%A6%E3%83%88%E3%81%8B}

キャンセルされる側の関数では、`Done`メソッドチャネルでキャンセルを認識した段階で後処理の実行に移ることが多いと思います。\
しかし、「明示的なキャンセルとタイムアウトによるキャンセルで、後処理を変えたい」という場合、現状の`Done`メソッドではそのどちらなのかを判断する術がありません。

::: code-block-container
``` language-go
func generator(ctx context.Context, num int) <-chan int {
    out := make(chan int)

    go func() {
        defer wg.Done()

    LOOP:
        for {
            select {
            case <-ctx.Done():
                // タイムアウトで止まったのか？
                // それともキャンセルされて止まったのか？
                // Doneメソッドだけでは判定不可
                break LOOP
            case out <- num:
            }
        }

        close(out)
        fmt.Println("generator closed")
    }()
    return out
}
```
:::

# [](#context%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AB%E5%AD%98%E5%9C%A8%E3%81%99%E3%82%8B2%E7%A8%AE%E9%A1%9E%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E5%A4%89%E6%95%B0){.header-anchor-link} contextパッケージに存在する2種類のエラー変数 {#context%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AB%E5%AD%98%E5%9C%A8%E3%81%99%E3%82%8B2%E7%A8%AE%E9%A1%9E%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC%E5%A4%89%E6%95%B0}

contextパッケージには、2種類のエラーが定義されています。

::: code-block-container
``` language-go
var Canceled = errors.New("context canceled")
var DeadlineExceeded error = deadlineExceededError{}
```
:::

出典:[pkg.go.dev
context-variables](https://pkg.go.dev/context#pkg-variables)

一つが`Canceled`で、contextが明示的にキャンセルされたときに使用されます。\
もう一つが`DeadlineExceeded`で、タイムアウトで自動キャンセルされた場合に使用されます。

また`DeadlineExceeded`には`Timeout`メソッドと`Temporary`メソッドがついており、`net.Error`インターフェースも追加で満たすようになっています。

::: code-block-container
``` language-go
// deadlineExceededError型の定義
type deadlineExceededError struct{}

func (deadlineExceededError) Error() string   { return "context deadline exceeded" }
func (deadlineExceededError) Timeout() bool   { return true }
func (deadlineExceededError) Temporary() bool { return true }
```
:::

出典:[context/context.go](https://github.com/golang/go/blob/master/src/context/context.go#L163-L167)

::: code-block-container
``` language-go
// net.Errorインターフェース
type Error interface {
    error
    Timeout() bool   // Is the error a timeout?
    Temporary() bool // Is the error temporary?
}
```
:::

出典:[pkg.go.dev - net pkg](https://pkg.go.dev/net#Error)

# [](#err%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89){.header-anchor-link} Errメソッド {#err%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89}

contextの`Err`メソッドからは、

-   contextがキャンセルされていない場合: `nil`
-   contextが明示的にキャンセルされていた場合: `Canceled`エラー
-   contextがタイムアウトしていた場合: `DeadlineExceeded`エラー

が得られるようになっています。

::: code-block-container
``` language-go
type Context interface {
    Err() error
    // (以下略)
}
```
:::

出典:[pkg.go.dev -
context.Context](https://pkg.go.dev/context@go1.17#Context)

そのため、前述した「明示的なキャンセルとタイムアウトによるキャンセルで、後処理を変えたい」という場合は、以下のように実現することができます。

::: code-block-container
``` language-go
select {
case <-ctx.Done():
    if err := ctx.Err(); errors.Is(err, context.Canceled) {
        // キャンセルされていた場合
        fmt.Println("canceled")
    } else if errors.Is(err, context.DeadlineExceeded) {
        // タイムアウトだった場合
        fmt.Println("deadline")
    }
}
```
:::
:::
:::
:::

